---
title: "RMD notebook"
author: "Meder Imanaliev"
date: "2024-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(psych)
library(dplyr)
library(tidyr)
library(stringi)
library(tibble)
library(ggplot2)
library(readr)
library(readxl)
```

getwd()
setwd("C:/Users/meder/OneDrive/Desktop/biostat/")

#Р‘Р°Р·РѕРІС‹Рµ СЃС‚Р°С‚РёСЃС‚РёРєРё

mean(c(20, 68, 45, 76, 41, 36, 13, 52, 77, 53, 70, 73))
median(c(30, 87, 55, -71, 93, 50, 34, -51, 13, 96, -62, 53, -85))
min(c(13, 50, 44, 37, 20, 29, -8, 4, 45, 31, 47, -5, -2, 24, 17, 45, 44, 31, -5, 26))
max(c(13, 50, 44, 37, 20, 29, -8, 4, 45, 31, 47, -5, -2, 24, 17, 45, 44, 31, -5, 26))
quantile(c(31.83, 45.12, 55.66, 67.76, 25.73, 42.87, 55.22, 44.92, 48.03, 41.37, 66.26, 114.02, 32.93))
sd(c(65.14, 49.87, 34.11, 43.23, 35.72, 35.73, 70.86))
length(1:10)

#СЃРµСЂСЉРµР·РЅР°СЏ СЂР°Р±РѕС‚Р° СЃ dataframe

 data <- read_tsv("data_tsv.tsv", skip = 0, n_max = Inf)

data %>%
  select("Р“СЂСѓРїРїР° РєСЂРѕРІРё", "Р РѕСЃС‚")
 
data %>%
  select(contains("_E1"))

data %>%
  select(where(is.numeric)) %>%
  select(where(function(x) sd(x, na.rm = TRUE) > 2 & mean(x, na.rm = TRUE) < 10))

data %>%
  select(`РџРѕР»`, `Р­СЂРёС‚СЂРѕС†РёС‚С‹_E1`, everything())

data %>%
slice (1:10)

data %>%
slice_head(n=10)

data %>%
slice_tail(prop=0.1)

data %>%
arrange("Р РѕСЃС‚")

data %>%
  select(`Р“СЂСѓРїРїР°`, contains("E1")) %>%
  pivot_longer(!`Р“СЂСѓРїРїР°`)

statistics <- list(
      `РљРѕР»РёС‡РµСЃС‚РІРѕ СЃСѓР±СЉРµРєС‚РѕРІ` = ~length(.x),
      `РљРѕР»РёС‡РµСЃС‚РІРѕ (РµСЃС‚СЊ РґР°РЅРЅС‹Рµ)` = ~sum(!is.na(.x)),
      `РќРµС‚ РґР°РЅРЅС‹С…` = ~sum(is.na(.x)),
      `РЎСЂ. Р·РЅР°С‡.` = ~ifelse(sum(!is.na(.x)) == 0, "Рќ/Рџ*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `РЎС‚Р°РЅРґ. РѕС‚РєР»РѕРЅ.` = ~ifelse(sum(!is.na(.x)) < 3, "Рќ/Рџ*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `95% Р”Р РґР»СЏ СЃСЂРµРґРЅРµРіРѕ` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `РјРёРЅ. - РјР°РєСЃ.` = ~ifelse(sum(!is.na(.x)) == 0, "Рќ/Рџ*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
      `РњРµРґРёР°РЅР°` = ~ifelse(sum(!is.na(.x)) == 0, "Рќ/Рџ*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Рќ/Рџ*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)


data %>%
  select('Р“СЂСѓРїРїР°', where(is.numeric)) %>%
  group_by('Р“СЂСѓРїРїР°') %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!'Р“СЂСѓРїРїР°', values_drop_na = TRUE) %>%
  separate(name, into = c("РџРµСЂРµРјРµРЅРЅР°СЏ", "РЎС‚Р°С‚РёСЃС‚РёРєР°"), sep = "__") %>%
  rename('Р—РЅР°С‡РµРЅРёРµ' = value)
  
  #Первый коммит
  #Второй коммит

